### ISSUE TITLE
Improvement for Project 13

### ISSUE THREAD

**Issue by Swastik-Sarkar** [israr96418/20_python_project#2]
```
def is_leap_year(year):
     """
     Check if a given year is a leap year.
    
    Args:
        year (int): The year to be checked.
    
    Returns:
        bool: True if the year is a leap year, False otherwise.
    """
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

if __name__ == '__main__':
    year = int(input('Enter the year that you want to check whether it is a leap year or not: '))
    if is_leap_year(year):
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")
```

===================================================================
Improvements Made:

Function Name and Structure: Function renamed to is_leap_year for more clarity in returning a boolean value and deleted the nested if-else structure to improve readability.

Docstring: Added a docstring with what the function does, its arguments, and return value

Simplified Condition: The condition has been re-written using logical operators for easy reading and less nesting.

Output Handling: Changed print statements to provide clear and concise output messages.

The above improvements have made the function easier to read, change, test, or use.

**Comment by israr96418** [comment]
Thanks @Swastik-Sarkar for improvement
